### ISSUE TITLE
Dark Blue Black gradient

### ISSUE THREAD

**Issue by mlangone** [phpbits/copygradients#1]
Subtle black to blue
background: linear-gradient(110.59deg, #000C22 12.48%, #000000 87.58%); 
Black and Purple angle
background: linear-gradient(339deg,#000 56%,#9013fe 0);
This one is more built for a class
      opacity: 0.80;
    background-image: linear-gradient(14deg, rgba(226, 115, 36, 1) 20%, #00B5E2 74%);
    mix-blend-mode: color;

**Comment by phpbits** [comment]
@mlangone Added except for this one `background: linear-gradient(339deg,#000 56%,#9013fe 0);`. Thanks a lot! Looking forward for more gradients :)
